server:
  port: 7777
spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: test

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: jMP4hgpKbdixKgY4Q5u-bj6sJmirR_1o7CfDg_27
  secretKey: GFrXotavFlRWqeaLbYO8ZNubSMPOiq-OSZrj9A4W
  bucket: lzx-blog-avatar
  url-prefix: http://cdn.xiaokabi.top/
